syntax error
cursor.execute(insert into users (name,age) values (%s, %s),(user.name,user.age))
                   ^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?